version: '3'
services:
  jupyter-tutorial:
    build: .
    container_name: jupyter.local
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_mission9:/home/jovyan/jupyter_mission9/
    command: start-notebook.sh --NotebookApp.token=''
  mariaDB-tutorial:
    image: mariadb
    container_name: cc104.rds.local
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
